name: project
channels:
  - conda-forge
  - default
dependencies:
  - pandas
  - numpy
  - matplotlib
  - wordcloud
  - python-dotenv
  - psycopg2-binary
  - sqlalchemy
  - postgresql
  - openai
  # - seaborn
  # - plotly
  # - altair
  # - vega_datasets
  # - scipy
  # - scikit-learn
  - jupyterlab
  # - jupyter
  # - beautifulsoup4
  - openpyxl
